services:
  # 1. Base de datos central (PostgreSQL)
  postgres-db:
    image: postgres:15-alpine
    container_name: analyticore-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: analyticore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Servicio de Análisis (Java)
  java-service:
    build: ./java-service
    container_name: analyticore-java
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres-db:5432/analyticore
      PORT: 8080
    depends_on:
      - postgres-db

  # 3. Servicio de Submisión (Python)
  python-service:
    build: ./python-service
    container_name: analyticore-python
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres-db:5432/analyticore
      JAVA_SERVICE_URL: http://java-service:8080
      PORT: 5000
    depends_on:
      - postgres-db
      - java-service

  # 4. Frontend Web (React + Nginx)
  frontend:
    build: ./frontend
    container_name: analyticore-frontend
    ports:
      - "3000:80"
    environment:
      PORT: 80
    depends_on:
      - python-service

volumes:
  pgdata:
